apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  # +optional Incoming connection details for the Ballerina compiler component.
  inbound:
    # +required Unique name for the Ballerina compiler endpoint.
    - name: Ballerina Compiler Integration
      # +required Numeric port value that gets exposed via the endpoint
      port: 8081
      # +required Type of traffic this endpoint is accepting. For the compiler, it will be a REST API.
      type: REST
      # +optional Network level visibility of the endpoint. Defaults to Public
      networkVisibility: Public
      # +optional Context (base path) for the API that will be exposed via the Ballerina compiler.
      context: /compile
      # +optional Path to the schema definition file. It can define the API paths.
      schemaFilePath: openapi.yaml
